apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: AutomationHub
      name: hub
    patch: |
      - op: replace
        path: /spec/web/replicas
        value: 2
      - op: replace
        path: /spec/api/replicas
        value: 2
