apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: db-controller
  annotations:
    argocd.argoproj.io/sync-wave: "15"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  name: aap_controller
  owner: app
  cluster:
    name: __replaced_by_site_config__
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: db-hub
  annotations:
    argocd.argoproj.io/sync-wave: "15"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  name: aap_hub
  owner: app
  cluster:
    name: __replaced_by_site_config__
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: db-eda
  annotations:
    argocd.argoproj.io/sync-wave: "15"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  name: aap_eda
  owner: app
  cluster:
    name: __replaced_by_site_config__
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: db-gateway
  annotations:
    argocd.argoproj.io/sync-wave: "15"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  name: aap_gateway
  owner: app
  cluster:
    name: __replaced_by_site_config__
