apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gateway-postgres-configuration
  annotations:
    argocd.argoproj.io/sync-wave: "17"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: local-secret-store
    kind: SecretStore
  target:
    name: gateway-postgres-configuration
    template:
      engineVersion: v2
      data:
        host: __replaced_by_site_config__
        port: "5432"
        database: aap_gateway
        username: "{{ .username }}"
        password: "{{ .password }}"
        sslmode: prefer
        type: unmanaged
  data:
    - secretKey: username
      remoteRef:
        key: __replaced_by_site_config__
        property: username
    - secretKey: password
      remoteRef:
        key: __replaced_by_site_config__
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: controller-postgres-configuration
  annotations:
    argocd.argoproj.io/sync-wave: "17"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: local-secret-store
    kind: SecretStore
  target:
    name: controller-postgres-configuration
    template:
      engineVersion: v2
      data:
        host: __replaced_by_site_config__
        port: "5432"
        database: aap_controller
        username: "{{ .username }}"
        password: "{{ .password }}"
        sslmode: prefer
        type: unmanaged
  data:
    - secretKey: username
      remoteRef:
        key: __replaced_by_site_config__
        property: username
    - secretKey: password
      remoteRef:
        key: __replaced_by_site_config__
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hub-postgres-configuration
  annotations:
    argocd.argoproj.io/sync-wave: "17"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: local-secret-store
    kind: SecretStore
  target:
    name: hub-postgres-configuration
    template:
      engineVersion: v2
      data:
        host: __replaced_by_site_config__
        port: "5432"
        database: aap_hub
        username: "{{ .username }}"
        password: "{{ .password }}"
        sslmode: prefer
        type: unmanaged
  data:
    - secretKey: username
      remoteRef:
        key: __replaced_by_site_config__
        property: username
    - secretKey: password
      remoteRef:
        key: __replaced_by_site_config__
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: eda-postgres-configuration
  annotations:
    argocd.argoproj.io/sync-wave: "17"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: local-secret-store
    kind: SecretStore
  target:
    name: eda-postgres-configuration
    template:
      engineVersion: v2
      data:
        host: __replaced_by_site_config__
        port: "5432"
        database: aap_eda
        username: "{{ .username }}"
        password: "{{ .password }}"
        sslmode: prefer
        type: unmanaged
  data:
    - secretKey: username
      remoteRef:
        key: __replaced_by_site_config__
        property: username
    - secretKey: password
      remoteRef:
        key: __replaced_by_site_config__
        property: password
