apiVersion: eda.ansible.com/v1alpha1
kind: EDA
metadata:
  name: eda
  namespace: aap
spec:
  automation_server_url: https://controller-aap.apps.placeholder.example.com
  replicas: 1
  ingress_type: Route
  route_tls_termination_mechanism: Edge
  image_pull_policy: IfNotPresent
