# ============================================================
#  Bootstrap ArgoCD Application
#  Edit repoURL below to point to your fork.
# ============================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aap-gitops
  namespace: openshift-gitops
spec:
  project: default
  source:
    # ====== EDIT THIS ======
    repoURL: https://github.com/christiancruz11/aap-gitops.git
    # =======================
    targetRevision: main
    path: site
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 10
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
