apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg-cluster
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/christiancruz11/aap-gitops.git
    targetRevision: main
    path: operands/cnpg
  destination:
    server: https://kubernetes.default.svc
    namespace: shared-postgresql
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
