apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aap-hub
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://REPLACE_WITH_YOUR_REPO_URL.git
    targetRevision: main
    path: components/hub/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: aap
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
